### ISSUE TITLE
[Bug]: Login behind proxy redirects to incorrect path

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#155]
When we deploy behind a proxy, we want to run at a subpath like `/apps/benefit-tool`. The app is informed of this through the `X-Forwarded-Prefix` header from the proxy.

Currently, this _does not_ work for login an logout (redirect is to `/`), but other links are OK. Looks like the "New survey link" also has problems.

**Comment by rmarow** [comment]
#165 resolved this issue for `login/logout` now just need to figure out `new_survey`

**Comment by rmarow** [comment]
open to ideas regarding `new_survey`. In QA when I click `new survey` it redirects to `https://qa.usaon.org/survey/new` , unlike `login/logout` the issue is not with `redirect` it seemingly is with the route itself which has me baffled because this uses the same `Blueprint` as `view_survey` with an additional endpoint. Thinking on it more tonight. @MattF-NSIDC

**Comment by MattF-NSIDC** [comment]
https://github.com/nsidc/usaon-vta-survey/blob/main/usaon_vta_survey/templates/surveys.html#L9

:)
